### ISSUE TITLE
certificate issue again

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-hangouts#211]
**[Original report](https://bitbucket.org/EionRobb/purple-hangouts/issue/211) by Alex (Bitbucket: [alexolog](https://bitbucket.org/alexolog), GitHub: [alexolog](https://github.com/alexolog)).**

----------------------------------------

A couple of days ago Pidgin started complaining abut the certificate for 0.client-channel.google.com.

**Comment by mpmilano** [comment]
FWIW This is still happening for me, though it's gotten rarer at least. No certificates could verify the google certificate for some reason.

**Comment by vwbusguy** [comment]
Yeah, this has been happening for me a bunch lately.  Sometimes several times a day.  If I miss clicking on all the pop ups, the accounts go disabled.  At risk of potential MITM, I'd almost wonder if it'd be worth it to have some kind of ignore validation on the certs if we can't get a proper CA trust.

**Comment by liskin** [comment]
Started happening for me as well since yesterday :-(

**Comment by mjeveritt** [comment]
Ditto

**Comment by ronansalmon** [comment]
I'm seeing this as well for about a week now. 

```
New request: Request: SSL Certificate Verification

Accept certificate for 0.client-channel.google.com?
The certificate for 0.client-channel.google.com could not be validated.

The certificate is not trusted because no certificate that can verify it is currently trusted.
You can use the yes/no commands to accept/reject this request.
```

It happens several times a day. this plugin becomes unusable.
I'm using the latest master branch.

What can I do to debug ?

**Comment by Deledrius** [comment]
> 
> I'm seeing this as well for about a week now.
> 
> What can I do to debug ?

Same.  Is there anything I can do to help, or at least workaround the problem?
