### ISSUE TITLE
Links to old repository in the wiki and readme

### ISSUE THREAD

**Issue by nekromoff** [EionRobb/purple-hangouts#220]
Including how to install parts referring to hg & mercurial.

Also, no information can be found on the latest version or any releases under github.

**Comment by EionRobb** [comment]
Whoops, thanks.  Still in the process of moving stuff off Bitbucket after the mercurial shutdown.

**Comment by nekromoff** [comment]
OK, thanks for that, I came back for more info on the recurring issue with
the hangout plugin, if there was an update. You can close this issue ofc.
And thanks again for the good work!

**Comment by gtTracy** [comment]
I don't see the new instructions on how to install/update the plugin under Ubuntu. The compile instructions in the readme and on the Wiki page still point to bitbucket.org, which just points back to the readme here, which points to bitbucket.org, which... Well, you see where I'm going with this.

Is there a procedure somewhere that I'm missing?

**Comment by nift4** [comment]
> I don't see the new instructions on how to install/update the plugin under Ubuntu. The compile instructions in the readme and on the Wiki page still point to bitbucket.org, which just points back to the readme here, which points to bitbucket.org, which... Well, you see where I'm going with this.
> 
> Is there a procedure somewhere that I'm missing?

```
sudo apt-get install -y libpurple-dev libjson-glib-dev libglib2.0-dev libprotobuf-c-dev protobuf-c-compiler mercurial make;
git clone https://github.com/EionRobb/purple-hangouts && cd purple-hangouts; # changed
make && sudo make install
```

**Comment by gtTracy** [comment]
Thanks. I was sure I had tried that, but wasn't able to get it to work. But it did this time, when I copied it from here, so maybe I typoed.

**Comment by nift4** [comment]
I bet you didn't remove the `/` at the end of the url, git doesn't like it

**Comment by EionRobb** [comment]
Hopefully that's all the places that need to be changed.

Feel free to post in this issue if there's elsewhere I missed or screwed up :)
